---
engines:
  structure:
    enabled: true
  duplication:
    enabled: true
    channel: cronopio
    config:
      languages:
      - java
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.java"
exclude_paths:
- "**.py*"
- "**.js"
- "**.rb"
